name: Bug
description: I found a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: description
    attributes:
      label: Bug Description
      description: Briefly describe the bug.
      placeholder: Doing X leads to a crash when Y is enabled...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How to reproduce the bug
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Hardware details
      description: Describe the hardware (e.g., DIY-built or specific model).
      placeholder: DIY-built (ESP32-S2 Mini, Arduino Leonardo), Digispark
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional information
      description: Add any extra context, links, or files.
      placeholder: I think this might be caused by ...
    validations:
      required: false