name: Question
description: I have a question about this project
title: "[Question]: "
labels: ["question"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for your question.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: question
    attributes:
      label: Your Question
      description: A concise question.
      placeholder: How can I do X?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional details
      description: Add extra details, links, or context if needed.
      placeholder: #
    validations:
      required: false